### ISSUE TITLE
Incorrect default steemd nodes

### ISSUE THREAD

**Issue by john-g-g** [Netherdrake/steem-python#1]
The `steemd.steemitstage.com` instance shouldn't be in the default list becuase it may be running a different steemd version or doing any other thing that staging envs get up to.

https://github.com/Netherdrake/steem-python/blob/master/steem/steemd.py#L55
```
nodes = get_config_node_list() or [
                'https://steemd.steemit.com',
                'https://steemd.steemitstage.com',
            ]
```
should be:
```
nodes = get_config_node_list() or ['https://steemd.steemit.com' ]
```

**Comment by Netherdrake** [comment]
Unfortunately, `https://steemd.steemitstage.com` is the only seemingly reliable backup. 
Without the backup to fall-back on, production software relying on this library's defaults will break (a lot).

**Comment by john-g-g** [comment]
Sorry, I created this on your fork, not the steemit repo. Please see [my issue](https://github.com/steemit/steem-python/issues/7) there for my response.
