### ISSUE TITLE
getting error importing account - steembase.storage.WrongMasterPasswordException

### ISSUE THREAD

**Issue by bitcoiners** [Netherdrake/steem-python#3]
Trying to import account gives error after asking for active key passphraze. I am sure putting correct active private key, but getting error.

```
steempy importaccount slavix
Account Passphrase: 
Importing active key!
Passphrase: 
Traceback (most recent call last):
  ...
steembase.storage.WrongMasterPasswordException


```

**Comment by Netherdrake** [comment]
The passphrase here is the one for your `steempy` or `piston` wallet, not the steem account.

**Comment by bitcoiners** [comment]
Thanks. Maybe it should be renamed wallet passphrase to make it clear.

**Comment by Netherdrake** [comment]
Not to self:
Improve the error message, to make it clear what the issue is.
